{% set name = "cobyqa" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cobyqa-{{ version }}.tar.gz
  sha256: 7c732d4009b49589acc4a53b2ede4e41bd0f36eab88e1dc628adaff8151ddc45

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - numpy >=1.17.0
    - scipy >=1.10.0

test:
  imports:
    - cobyqa
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cobyqa/cobyqa
  doc_url: https://www.cobyqa.com
  dev_url: https://github.com/cobyqa/cobyqa
  doc_source_url: https://github.com/cobyqa/cobyqa/blob/main/README.rst
  summary: Constrained Optimization BY Quadratic Approximations
  description: COBYQA is a derivative-free optimization solver for general optimization.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ragonneau
    - zaikunzhang
