{% set name = "cobyqa" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cobyqa-{{ version }}.tar.gz
  sha256: 3812a2a2ab73c243abf462f75a846aa567ca2a1e35ffe6a8208f3b46df2b664b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - numpy >=1.17.0
    - scipy >=1.10.0

test:
  imports:
    - cobyqa
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cobyqa/cobyqa
  doc_url: https://www.cobyqa.com
  dev_url: https://github.com/cobyqa/cobyqa
  summary: Constrained Optimization BY Quadratic Approximations
  description: COBYQA is a derivative-free optimization solver for general optimization.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ragonneau
